# Container image for running the Ceph-CSI tests
#
# This container is based on Fedora so that recent versions of tools can easily
# be installed.
#
# Production containers are based one ceph/ceph:latest, which use CentOS as
# Operating System, so generated binaries and versions of dependencies may be a
# little different.
#
FROM quay.ceph.io/ceph-ci/ceph:wip-rbd-cgsm-base

ARG GOPATH=/go
ARG GOROOT=/usr/local/go
ARG GOARCH

ENV \
 GOPATH=${GOPATH} \
 GOROOT=${GOROOT} \
 GO111MODULE=on \
 CEPHCSIPATH=/go/src/github.com/ceph/ceph-csi \
 PATH="${GOPATH}/bin:${GOROOT}/bin:/opt/commitlint/node_modules/.bin:${PATH}"

COPY build.env /

RUN mkdir -p /etc/selinux && touch /etc/selinux/config

RUN true \
    && (. /etc/os-release ; if [ "$ID" = centos -a "$VERSION" = 8 ]; then find /etc/yum.repos.d/ -name '*.repo' -exec sed -i -e 's|^mirrorlist=|#mirrorlist=|g' -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://vault.centos.org|g'  {} \; ; fi ) \
    && if [ ! -f /etc/yum.repos.d/ceph.repo -a "$CEPH_IS_DEVEL" = true ]; then if [ -z "$CEPH_SHA1" ]; then CEPH_SHA1="$(sed -n 's/.*CEPH_GIT_VER *= *"\(.*\)".*/\1/p' /usr/bin/ceph)"; fi ; yum reinstall -y "$(curl -fs "https://shaman.ceph.com/api/search/?project=ceph&distros=centos/9/x86_64&flavor=default&ref=${CEPH_REF}&sha1=${CEPH_SHA1:-latest}" | jq -r .[0].url)/noarch/ceph-release-1-0.el9.noarch.rpm"; fi \
    && if [ ! -f /etc/yum.repos.d/ceph.repo -a "$CEPH_IS_DEVEL" != true ]; then yum reinstall -y "https://download.ceph.com/rpm-${CEPH_REF}/el9/noarch/ceph-release-1-1.el9.noarch.rpm"; fi \
     && ( dnf config-manager --disable tcmu-runner,tcmu-runner-source,tcmu-runner-noarch,ceph-iscsi,ganesha || true ) \
     && true

RUN set -x \
    && source /build.env \
    && \
    ( test -n "${GOARCH}" && exit 0; echo -e "\n\nMissing GOARCH argument for building image, install Golang or run: make containerized-test GOARCH=amd64\n\n"; exit 1 ) \
    && dnf -y install \
	git \
	make \
	gcc \
	findutils \
	librados-devel \
        libcephfs-devel \
	librbd-devel \
	openssl \
	ruby-devel \
	rubygems \
	ShellCheck \
	codespell \
	yamllint \
	npm \
	diffutils \
	python3-prettytable \
	pylint \
    && dnf -y update \
    && dnf -y clean all \
    && gem install mdl -v 0.15.0 \
    && mkdir -p ${GOROOT} \
    && curl -L https://go.dev/dl/go${GOLANG_VERSION}.linux-${GOARCH}.tar.gz  \
       | tar xzf - -C ${GOROOT} --strip-components=1 \
    && go version \
    && curl -sf "https://raw.githubusercontent.com/golangci/golangci-lint/${GOLANGCI_VERSION}/install.sh" \
       | bash -s -- -b ${GOPATH}/bin "${GOLANGCI_VERSION}" \
    && curl -L "${HELM_SCRIPT}" | bash -s -- --version "${HELM_VERSION}" \
    && mkdir /opt/commitlint && pushd /opt/commitlint \
    && npm init -y \
    && npm install @commitlint/cli@"${COMMITLINT_VERSION}" \
    && popd \
    && ARCH=$(case "${GOARCH}" in amd64) echo "x86_64";; arm64) echo "aarch64";; *) echo "x86_64";; esac) \
    && curl -sSfL "https://github.com/lycheeverse/lychee/releases/download/lychee-${LYCHEE_VERSION}/lychee-${ARCH}-unknown-linux-gnu.tar.gz" | tar -xz -C /usr/local/bin \
    && git config --global --add safe.directory ${CEPHCSIPATH} \
    && go install github.com/augmentable-dev/tickgit/cmd/tickgit@latest \
    && true

WORKDIR ${CEPHCSIPATH}
